spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:13306/research
    username: root
    password: password


doma:
  dialect: MYSQL
  sql-file-repository: no_cache
